In [1]:
import numpy as np  

import sys
import subprocess
sys.path.append("/home/talax/xtof/local/Mod/lib64")
from mod import *
# from utils import smarts_to_gml_with_mapping
import random
from rdkit.Chem import AllChem,Draw
import numpy as np
from rdkit import Chem
# from rdchiral.main import rdchiralRun, rdchiralReaction, rdchiralReactants
import pandas as pd 
import sknetwork as skn
from utils import smarts_to_gml

: 

In [3]:
asp  = smiles('OC(=O)CC(N)C(=O)O', 'ASP')
lys  = smiles('NCCCCC(N)C(=O)O', 'LYS')
akg  = smiles('OC(=O)C(=O)CCC(=O)O', 'AKG')  
pyr  = smiles('CC(=O)C(=O)O', 'PYR')
lac  = smiles('CC(O)C(=O)O', 'LAC')
aca  = smiles('CC=O', 'AcA')
ac   = smiles('CC(=O)O', 'Ac')
mal  = smiles('OC(=O)C(O)CC(=O)O','MAL')
co2  = smiles('O=C=O', 'CO2')
pi   = smiles('OP(=O)(O)O', 'Pi')
ppi  = smiles('OP(=O)(O)OP(=O)(O)O', 'PPi')
nh3  = smiles('[NH3]', 'NH3')
h2o  = smiles('O', 'H2O')
hco3 = smiles('OC(=O)O', 'HCO3') 
hp = smiles('[H+]', 'H+')

coa     = graphDFS('[CoA]S[H]', 'CoA')
sam     = graphDFS('[Ad][S+](C)CCCN', 'SAM')
nadh    = graphDFS('[NAD][H]', 'NADH')
nadplus = graphDFS('[NAD+]', 'NAD+')
atp     = graphDFS('[Ad]OP(=O)(O)OP(=O)(O)OP(=O)(O)O', 'ATP')
accoa   = graphDFS('[CoA]SC(=O)C', 'Ac-CoA')
laccoa  = graphDFS('[CoA]SC(=O)C(O)C', 'LAC-CoA')

# for m in inputGraphs:
#     m.print()

# rules(s)


In [4]:
# with open('rules.gml', 'r') as f:
#     rules_set = []
#     rules = f.read()
#     for rule in rules.split('\n \n \n'):
#         rules_set.append(ruleGMLString(rule))
        
# rules_set 
r1  = ruleGML('/home/mescalin/yitao/Documents/Code/3HPspace/rule-0001.gml')
# r2  = ruleGML('/home/mescalin/yitao/Documents/Code/3HPspace/rule-0002.gml')
# r3  = ruleGML('/home/mescalin/yitao/Documents/Code/3HPspace/rule-0003.gml')
# r4  = ruleGML('/home/mescalin/yitao/Documents/Code/3HPspace/rule-0004.gml')
# r5  = ruleGML('/home/mescalin/yitao/Documents/Code/3HPspace/rule-0005.gml')
# r6  = ruleGML('/home/mescalin/yitao/Documents/Code/3HPspace/rule-0006.gml')
# r7  = ruleGML('/home/mescalin/yitao/Documents/Code/3HPspace/rule-0007.gml')
# r8  = ruleGML('/home/mescalin/yitao/Documents/Code/3HPspace/rule-0008.gml')
# r9  = ruleGML('/home/mescalin/yitao/Documents/Code/3HPspace/rule-0009.gml')
# r10 = ruleGML('/home/mescalin/yitao/Documents/Code/3HPspace/rule-0010.gml')
# r11 = ruleGML('/home/mescalin/yitao/Documents/Code/3HPspace/rule-0011.gml')




In [14]:
# p = GraphPrinter()
# p.setReactionDefault()
# p.withIndex = True
# for r in inputRules:
#     r.print(p)

In [25]:
strat = (addSubset(inputGraphs) >> repeat[1]([r1]))
dg = DG(graphDatabase=inputGraphs)
# dg.build().execute(strat)
dg.build().apply(inputGraphs, r1,onlyProper=False)


In [27]:

for v in dg.vertices:
    print(v.graph.name)
    print(v.graph.id)

dg.print()

LAC
4
NAD+
18
PYR
3
H+
14
NADH
17
MAL
7
p_{9,0}
50


LogicError: Can not open file 'out/000_dg_9_11100.dot'.

In [ ]:

hypergraph = []
for e in dg.edges:
    rule = set()
    for r in e.rules:
        rule.add("R" + str(r.id +1))
        
    source = set()
    for s in e.sources:
        source.add(s.graph.id)
    
    target = set()
    for t in e.targets:
        target.add(t.graph.id)
    hypergraph.append([rule, source, target])
    print(hypergraph[-1])


[{'R1'}, {18, 4}, {17, 3, 14}]
[{'R1'}, {18, 7}, {17, 26, 14}]
[{'R2'}, {18, 5, 15}, {17, 20, 14}]
[{'R3'}, {0, 2}, {32, 31}]
[{'R4'}, {12, 20}, {6, 15}]
[{'R4'}, {12, 21}, {4, 15}]
[{'R5'}, {8, 16}, {37}]
[{'R6'}, {7}, {12, 39}]
[{'R7'}, {21}, {43, 12}]
[{'R8'}, {0}, {11, 39}]
[{'R9'}, {1}, {57}]
[{'R10'}, {0, 19, 15}, {65, 10, 67}]
[{'R10'}, {0, 19, 15}, {73, 65, 10}]
[{'R10'}, {1, 19, 15}, {65, 10, 79}]
[{'R10'}, {2, 19, 15}, {65, 10, 85}]
[{'R10'}, {2, 19, 15}, {65, 10, 91}]
[{'R10'}, {19, 3, 15}, {65, 10, 97}]
[{'R10'}, {19, 4, 15}, {65, 10, 21}]
[{'R10'}, {19, 6, 15}, {65, 10, 20}]
[{'R10'}, {19, 15, 7}, {65, 10, 115}]
[{'R10'}, {19, 15, 7}, {65, 10, 121}]
[{'R11'}, {19, 20, 13}, {9, 125, 127}]
[{'R11'}, {21, 19, 13}, {9, 134, 127}]
[{'R1'}, {121, 18}, {17, 138, 14}]
[{'R2'}, {32, 18, 15}, {17, 141, 14}]
[{'R4'}, {43, 12}, {143, 15}]
[{'R4'}, {67, 12}, {0, 15}]
[{'R4'}, {73, 12}, {0, 15}]
[{'R4'}, {12, 79}, {1, 15}]
[{'R4'}, {12, 85}, {2, 15}]
[{'R4'}, {91, 12}, {2, 15}]
[{'R4'},

In [ ]:
from shortest_path_bipartite import *

Q1,Q2,V,H = hypergraph_to_bipartite(hypergraph)
print(Q1.shape)
print(Q2.shape)
print(V)

print(H)


# P1_2m1, Q1_2m1, Q2_2m1, P2_2m1 = torgansin_zimmerman(Q1,Q2)
# print(P1_2m1)
# print(Q1_2m1)
# print(Q2_2m1)
# print(P2_2m1)


torch.Size([11, 108])
torch.Size([108, 11])
{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15, 16: 16, 17: 17, 18: 18, 19: 19, 20: 20, 21: 21, 26: 22, 31: 23, 32: 24, 37: 25, 39: 26, 43: 27, 57: 28, 65: 29, 67: 30, 73: 31, 79: 32, 85: 33, 91: 34, 97: 35, 115: 36, 121: 37, 125: 38, 127: 39, 134: 40, 138: 41, 141: 42, 143: 43, 179: 44, 183: 45, 187: 46, 189: 47, 193: 48, 199: 49, 205: 50, 208: 51, 211: 52, 214: 53, 217: 54, 223: 55, 226: 56, 232: 57, 238: 58, 244: 59, 247: 60, 257: 61, 263: 62, 269: 63, 275: 64, 281: 65, 287: 66, 293: 67, 299: 68, 302: 69, 305: 70, 307: 71, 308: 72, 312: 73, 323: 74, 331: 75, 395: 76, 399: 77, 403: 78, 407: 79, 411: 80, 415: 81, 419: 82, 423: 83, 425: 84, 431: 85, 435: 86, 463: 87, 471: 88, 501: 89, 507: 90, 513: 91, 516: 92, 519: 93, 522: 94, 525: 95, 528: 96, 531: 97, 534: 98, 537: 99, 540: 100, 543: 101, 546: 102, 556: 103, 634: 104, 640: 105, 646: 106, 652: 107}
{'R1': 0, 'R2': 1, 'R3': 2, 'R4

In [ ]:
mol_dict = get_mol_dict(dg)
print(mol_dict)

{0: 'ASP', 1: 'LYS', 2: 'AKG', 3: 'PYR', 4: 'LAC', 5: 'AcA', 6: 'Ac', 7: 'MAL', 8: 'CO2', 9: 'Pi', 10: 'PPi', 11: 'NH3', 12: 'H2O', 13: 'HCO3', 14: 'H+', 15: 'CoA', 16: 'SAM', 17: 'NADH', 18: 'NAD+', 19: 'ATP', 20: 'Ac-CoA', 21: 'LAC-CoA', 23: 'p_{0,0}', 26: 'p_{0,1}', 27: 'p_{0,2}', 31: 'p_{0,3}', 33: 'p_{0,4}', 35: 'p_{0,5}', 38: 'p_{0,6}', 40: 'p_{0,7}', 41: 'p_{0,8}', 43: 'p_{0,9}', 45: 'p_{0,10}', 47: 'p_{0,11}', 49: 'p_{0,12}', 51: 'p_{0,13}', 55: 'p_{0,14}', 57: 'p_{0,15}', 59: 'p_{0,16}', 60: 'p_{0,17}', 62: 'p_{0,18}', 64: 'p_{0,19}', 66: 'p_{0,20}', 68: 'p_{0,21}', 78: 'p_{0,22}', 80: 'p_{0,23}', 82: 'p_{0,24}', 84: 'p_{0,25}', 86: 'p_{0,26}', 88: 'p_{0,27}', 91: 'p_{0,28}', 93: 'p_{0,29}', 95: 'p_{0,30}', 97: 'p_{0,31}', 99: 'p_{0,32}', 102: 'p_{0,33}', 104: 'p_{0,34}', 107: 'p_{0,35}', 110: 'p_{0,36}', 113: 'p_{0,37}', 115: 'p_{0,38}', 118: 'p_{0,39}', 120: 'p_{0,40}', 122: 'p_{0,41}', 124: 'p_{0,42}', 126: 'p_{0,43}', 128: 'p_{0,44}', 130: 'p_{0,45}', 132: 'p_{0,46}', 134:

In [ ]:


for e in dg.edges:
    for r,s,t in zip(e.rules, e.sources, e.targets):
        print(r.id, r.name)
        print(s.graph,s.graph.id,s.graph.name,s.graph.linearEncoding)
        print(t.graph, t.graph.id,t.graph.name,t.graph.linearEncoding)
        


post.flushCommands()
# generate summary/summery.pdf
subprocess.run(["/home/talax/xtof/local/Mod/bin/mod_post"])

: 

In [ ]:
shortest_path = pd.read_csv('shortest_path_r.csv', header=None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
# shortest_path

In [ ]:
# shortest_path_arr = shortest_path.to_numpy()
# vsp = shortest_path_arr[11:,11:]

# vsp_df = pd.DataFrame(vsp)
# vsp_df

In [ ]:
shortest_path_ = pd.read_csv('shortest_path_v.csv', header=None)

shortest_path_

0    1    2    3    4    5    6    7    8    9    10   11   12   \
0         NaN  ASP  LYS  AKG  PYR  LAC  AcA   Ac  MAL  CO2   Pi  PPi  NH3   
1         ASP  0.0  2.0  2.0  2.0  2.0  inf  2.0  2.0  inf  2.0  1.0  1.0   
2         LYS  2.0  0.0  2.0  2.0  2.0  inf  2.0  2.0  inf  2.0  1.0  3.0   
3         AKG  2.0  2.0  0.0  2.0  2.0  inf  2.0  2.0  inf  2.0  1.0  3.0   
4         PYR  2.0  2.0  2.0  0.0  2.0  inf  2.0  2.0  inf  2.0  1.0  3.0   
5         LAC  2.0  2.0  2.0  1.0  0.0  inf  2.0  2.0  inf  2.0  1.0  3.0   
6         AcA  2.0  2.0  2.0  2.0  2.0  0.0  2.0  2.0  inf  2.0  2.0  3.0   
7          Ac  2.0  2.0  2.0  2.0  2.0  inf  0.0  2.0  inf  2.0  1.0  3.0   
8         MAL  2.0  2.0  2.0  1.0  2.0  inf  2.0  0.0  inf  2.0  1.0  3.0   
9         CO2  3.0  3.0  3.0  3.0  3.0  inf  3.0  3.0  0.0  3.0  2.0  4.0   
10         Pi  inf  inf  inf  inf  inf  inf  inf  inf  inf  0.0  inf  inf   
11        PPi  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  0.0  inf   
12        NH3  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  0.0   
13        H2O  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  2.0  2.0  2.0   
14       HCO3  2.0  2.0  2.0  2.0  2.0  inf  2.0  2.0  inf  1.0  2.0  2.0   
15         H+  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf   
16        CoA  2.0  2.0  2.0  2.0  2.0  inf  2.0  2.0  inf  2.0  1.0  3.0   
17        SAM  3.0  3.0  3.0  3.0  3.0  inf  3.0  3.0  inf  3.0  2.0  4.0   
18       NADH  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf   
19       NAD+  2.0  2.0  2.0  1.0  2.0  inf  2.0  2.0  inf  2.0  2.0  3.0   
20        ATP  2.0  2.0  2.0  2.0  2.0  inf  2.0  2.0  inf  1.0  1.0  2.0   
21     Ac-CoA  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  1.0  2.0  2.0   
22    LAC-CoA  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  1.0  2.0  2.0   
23    p_{0,0}  2.0  2.0  2.0  2.0  2.0  inf  2.0  2.0  inf  2.0  1.0  3.0   
24    p_{0,1}  2.0  2.0  2.0  2.0  2.0  inf  2.0  2.0  inf  2.0  1.0  3.0   
25    p_{0,2}  2.0  2.0  2.0  2.0  2.0  inf  2.0  2.0  inf  2.0  1.0  3.0   
26    p_{0,3}  2.0  2.0  2.0  2.0  2.0  inf  2.0  2.0  inf  2.0  1.0  3.0   
27    p_{0,4}  2.0  2.0  2.0  2.0  2.0  inf  2.0  2.0  inf  2.0  1.0  3.0   
28    p_{0,5}  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  1.0  2.0  2.0   
29    p_{0,6}  2.0  2.0  2.0  2.0  2.0  inf  2.0  2.0  inf  2.0  1.0  3.0   
30    p_{0,7}  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf   
31    p_{0,8}  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  1.0  1.0  2.0   
32    p_{0,9}  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  1.0  1.0  2.0   
33   p_{0,10}  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  1.0  2.0  2.0   
34   p_{0,11}  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  2.0  1.0  2.0   
35   p_{0,12}  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  1.0  1.0  2.0   
36   p_{0,13}  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  2.0  2.0  2.0   
37   p_{0,14}  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  1.0  1.0  2.0   
38   p_{0,15}  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  1.0  1.0  2.0   
39   p_{0,16}  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  1.0  1.0  2.0   
40   p_{0,17}  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf   
41   p_{0,18}  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  2.0  1.0  2.0   
42   p_{0,19}  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  1.0  1.0  2.0   
43   p_{0,20}  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  1.0  1.0  2.0   
44   p_{0,21}  2.0  2.0  2.0  2.0  2.0  inf  2.0  2.0  inf  2.0  1.0  3.0   
45   p_{0,22}  2.0  2.0  2.0  2.0  2.0  inf  2.0  2.0  inf  2.0  1.0  3.0   
46   p_{0,23}  2.0  2.0  2.0  2.0  2.0  inf  2.0  2.0  inf  2.0  1.0  3.0   
47   p_{0,24}  2.0  2.0  2.0  2.0  2.0  inf  2.0  2.0  inf  2.0  1.0  3.0   
48   p_{0,25}  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  1.0  1.0  2.0   
49   p_{0,26}  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  2.0  1.0  2.0   
50   p_{0,27}  1.0  1.0  1.0  1.0  1.0  inf  1.0  1.0  inf  2.0  1.0  2.0   
51   p

In [26]:
dict1 = {'ASP': 0, 'LYS': 1}
dict2 = {'R1': 0, 'R2': 1}

# Using the update method
# dict1.update(dict2)
d = dict2 | dict1
# Print the updated dictionary
print("Merged Dictionary:", dict1)
print(d)

Merged Dictionary: {'ASP': 0, 'LYS': 1}
{'R1': 0, 'R2': 1, 'ASP': 0, 'LYS': 1}


In [12]:
import torch
import torch.nn.functional as F

# Create a non-contiguous tensor
x = torch.tensor([[1, 2], [3, 4]])

# Create a contiguous copy using contiguous()
x1 = F.one_hot(torch.tensor(5), num_classes=8)
print(x1)
x2 = torch.tensor([torch.rand(8).numpy(), torch.rand(8).numpy()],
                    dtype=torch.float).t().contiguous()
print(x2)
x = torch.cat([x1.to(torch.float), x2], dim=-1)
x

tensor([0, 0, 0, 0, 0, 1, 0, 0])
tensor([[0.3256, 0.5949],
        [0.0562, 0.1584],
        [0.4135, 0.4951],
        [0.1168, 0.1567],
        [0.8768, 0.2911],
        [0.5473, 0.0086],
        [0.1784, 0.2520],
        [0.0017, 0.1122]])


/tmp/ipykernel_133023/908241827.py:10: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /opt/conda/conda-bld/pytorch_1699449201450/work/torch/csrc/utils/tensor_new.cpp:261.)
  x2 = torch.tensor([torch.rand(8).numpy(), torch.rand(8).numpy()],


RuntimeError: Tensors must have same number of dimensions: got 1 and 2

In [5]:
torch.rand(8)

tensor([0.3597, 0.7523, 0.2243, 0.6790, 0.1174, 0.8921, 0.2635, 0.6930])